version: "3"

services:
  frontend:
    command: "sh -c 'npm install && npm run dev'"

  api:
    command: "sh -c 'npm install && npm run dev'"
    environment:
      - PORT=3001
      - HOST=docker.local
      - MONGO_URL=mongodb://api_db:27017/api

  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf